### ISSUE TITLE
Black preview of 95Kb

### ISSUE THREAD

**Issue by atwright147** [myfreeweb/exiv2node#2]
I have been playing with your fork and I am struggling to get a preview out of it. I have created an experimental repo here: https://github.com/atwright147/exiv2node-test

It's probably my code but I cannot see what is wrong.  I have also tried using your example code with `fs.writeFile()` and `fs.writeFileSync()` but all gave the same result.

PS. The preview is always 95Kb too.

**Comment by valpackett** [comment]
Maybe your image viewer is broken? I just ran the code from your repo and got a working image.

**Comment by valpackett** [comment]
Here's the image btw https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/preview.tif

**Comment by atwright147** [comment]
Interesting.

Your preview is broken for me on two different Macs in: Preview, Finder (probably uses Preview too) and Photoshop CC 2015 and CC 2017.

Here is what Photoshop says:
![screen shot 2017-07-03 at 11 37 12](https://user-images.githubusercontent.com/986665/27789383-4e92c054-5fe4-11e7-8ad0-dabbd2f9c1b9.png)

I have not tried on Windows yet but either way this seems broken. Could it be my code or is there an issue in the package?

**Comment by valpackett** [comment]
It works fine in Windows Photo Viewer.

It's not code or the package, it's the data that's in dng file. Maybe it's not actually TIFF or something. Run imagemagick's identification thing!

**Comment by atwright147** [comment]
That's an interesting point, Photoshop is talking about a JPEG

**Comment by atwright147** [comment]
Just ran it (I removed the file extension to ensure that it wasn't being influenced by that) and got the following:

```sh
gm identify preview
preview TIFF 1024x683+0+0 DirectClass 8-bit 92.6Ki 0.000u 0m:0.000002s
```

So, according to `gm` it is a TIFF.

What happens if you open the preview in a different image app (Photoshop, Gimp or something else)?

**Comment by atwright147** [comment]
I am definitely not getting a full image out. The image below is a Diff between the preview.tif output from my repo and the preview output from running: `exiv2 -ep2 source.dng`

The node one is missing some data.
<img width="1871" alt="exix2 cli vs exiv2node (via buffer)" src="https://user-images.githubusercontent.com/986665/27802754-a4b5d9d8-601d-11e7-9180-ee5aa1d7db48.png">

> exiv2node (left) vs exiv2 cli (right)

**Comment by valpackett** [comment]
Somehow Windows is able to read it without the extra data…

I guess you'll have to have your app convert the images to another (or same) format :D

**Comment by atwright147** [comment]
I don't think that is going to work because it is an invalid image.

Is there no way to fix this? Anything I can do to help?

**Comment by valpackett** [comment]
It's not really invalid. If Windows photo viewer can open it, surely some library (libvips, imagemagick, graphicsmagick) can too!

**Comment by valpackett** [comment]
try https://github.com/lovell/sharp in particular for a libvips based node module

**Comment by atwright147** [comment]
Yeah, I'm a big fan of sharp and I am already using it in my app.

Please don't be offended but I'm afraid I have to disagree with you there.
A file with obviously missing content, whether it can be read by one other
app or not is still only a partial file. And who knows what important data
is in that bit of the file.

The way I see it, there are only two things that could be going wrong here,
either your code is truncating something off the end or exiv2's C API is.
Since I have experienced this before in the original exiv2node package, I
must conclude that the exiv2node API is the culprit.

I would like to raise this with the exiv2 Devs and see if they can fix it;
would you be willing to help me with this?

PS. I really appreciate your incredible effort on this :-)

**Comment by valpackett** [comment]
Maybe the exiv2 CLI actually does some extra processing to *add* data?

(also my effort is really small :D i only added buffer support because I needed that.)

**Comment by atwright147** [comment]
In that case, I would think that the API should do the same and if not maybe we could replicate it?

I wouldn't know how to do that, so in my eyes it's pretty epic :D

**Comment by clanmills** [comment]
Gentlemen:  Can you attach a test file to this issue, please?  I'm very surprised by what's being discussed.  I will investigate this today when you provide a suitable test image.

**Comment by clanmills** [comment]
I found your test file source.dng and commented on it here:  https://github.com/Exiv2/exiv2/issues/16

**Comment by valpackett** [comment]
Fixed by 393be366

**Comment by atwright147** [comment]
Oh my God! That's awesome! It totally works :)

The refactor to get these changes in has screwed my app but I'll sort that out soon enough

**Comment by clanmills** [comment]
Good things happen when we pull together. In software, 1+1=3.
